version: "3.9"

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/hosts:/etc/nginx/conf.d
        links:
            - apache2
        depends_on:
            - apache2

    apache2:
        container_name: apache2
        image: apache2image
        build:
            context: .
            dockerfile: docker/apache2/DockerFile
        volumes:
            - ./:/var/www

    percona:
        container_name: percona
        platform: linux/amd64 # чит для АРМ М1
        image: percona
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: laravel